name: gh pages
on:
  push:
    branches:
      - gh-workflow

jobs:
  build-deploy-gh-pages:
    name: Build / Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build
      - name: Deploy frontend to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          cname: solderq35.github.io
          allow_empty_commit: true
